services:
  app:
    container_name: anonymousstudentreviews.api
    build:
      context: .
      dockerfile: src/AnonymousStudentReviews.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${SSL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${SSL_CERTIFICATE_FOLDER_PATH}:/https:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17.5-alpine
    container_name: anonymousstudentreviews.database
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d database -h localhost"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

volumes:
  pgdata:
