name: Backend CI

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set SHORT_SHA & BRANCH_NAME
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CI Image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: build
          load: true
          tags: backend-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Checks and Tests in Container
        run: |
          docker run --name ci-container backend-ci bash -c " \
            dotnet format --verify-no-changes || true && \
            dotnet build -c Release && \
            dotnet test --no-build -c Release --collect:\"XPlat Code Coverage\" --results-directory /src/TestResults \
          "

      - name: Extract coverage
        if: always()
        run: |
          docker cp ci-container:/src/TestResults ./TestResults || true
          docker rm -f ci-container || true

      - name: Report coverage
        if: always()
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: "TestResults/**/coverage.cobertura.xml"
          targetdir: "coveragereport"
          reporttypes: "HtmlInline_AzurePipelines;Cobertura"

      - name: Upload coverage report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport

      - name: Check vulnerable packages in Container
        run: docker run --rm backend-ci dotnet list package --vulnerable || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github_actions_oidc
          role-session-name: GHA_DOCKER_PUSH
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push final image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/backend:${{ env.BRANCH_NAME }}
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/backend:${{ env.BRANCH_NAME }}-${{ env.SHORT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
